apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-nginx
  template:
    metadata:
      labels:
        app: ms-nginx
    spec:
      containers:
        - image: rsobook/ms-nginx:2.0.5
          name: ms-nginx
          env:
            - name: PORT
              value: '80'

            - name: IMAGES_BASE_URL
              value: '/api/v1/Images'
            - name: IMAGES_SERVCIE_URL
              value: 'ms-images.default.svc.cluster.local'

            - name: FRIENDS_BASE_URL
              value: '/api/v1/Friends'
            - name: FRIENDS_SERVCIE_URL
              value: 'ms-friends.default.svc.cluster.local'

            - name: ADS_BASE_URL
              value: '/api/v1/Ads'
            - name: ADS_SERVCIE_URL
              value: 'ms-ads.default.svc.cluster.local'

            - name: WALL_BASE_URL
              value: '/api/v1/Wall'
            - name: WALL_SERVCIE_URL
              value: 'ms-wall.default.svc.cluster.local'

            - name: CHATROOM_BASE_URL
              value: '/api/v1/ChatRoom'
            - name: CHATROOM_SERVCIE_URL
              value: 'ms-chatroom.default.svc.cluster.local'

            - name: CHATRELAY_BASE_URL
              value: '/api/v1/ChatRelay'
            - name: CHATRELAY_SERVCIE_URL
              value: 'ms-chatrelay.default.svc.cluster.local'

            - name: USER_BASE_URL
              value: '/api/v1/User'
            - name: USER_SERVCIE_URL
              value: 'ms-user.default.svc.cluster.local'

            - name: ABOUT_BASE_URL
              value: '/api/v1/About'
            - name: ABOUT_SERVCIE_URL
              value: 'ms-about.default.svc.cluster.local'

            - name: RESOLVER
              value: '172.21.0.10 valid=10s'

          ports:
          - containerPort: 5432
            protocol: TCP